name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Log in to Docker Hub securely
      run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u parag7 --password-stdin

    - name: Build Docker Image
      run: |
        docker build -t parag7/simpletraining:latest .

    - name: Push Docker Image to Docker Hub
      run: |
        docker push parag7/simpletraining:latest

    - name: Run Docker Compose
      run: docker-compose up -d
